// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatepublic = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Cinnabar REST API Support",
            "url": "https://cinnabar.icaksh.my.id/",
            "email": "me@icaksh.my.id"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}",
        "x-logo": {
            "altText": "Cinnabar REST API",
            "backgroundColor": "#ffffff",
            "url": "https://cinnabar.icaksh.my.id/view/logo.png"
        }
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/daily/tawiki": {
            "get": {
                "description": "Sumber: Wikipedia Bahasa Indonesia",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "information"
                ],
                "summary": "Wikipedia - Tahukah Anda",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/public.TResTAWiki"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/public.TErrTAWiki"
                        }
                    }
                }
            }
        },
        "/latest/gempa": {
            "get": {
                "description": "Sumber: Badan Meteorologi, Klimatologi, dan Geofisika Republik Indonesia",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "information"
                ],
                "summary": "BMKG - Gempa Terbaru",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/public.TResLatestEarthquake"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/public.TErrLatestEarthquake"
                        }
                    }
                }
            }
        },
        "/test": {
            "get": {
                "description": "Cinnabar REST API JSON Format",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "basic"
                ],
                "summary": "REST - Response",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.TErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.TErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.TErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {}
            }
        },
        "model.TSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {}
            }
        },
        "public.TErrLatestEarthquake": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "kode error untuk dikirimkan ke pengelola",
                    "type": "integer"
                }
            }
        },
        "public.TErrTAWiki": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "kode error untuk dikirimkan ke pengelola",
                    "type": "integer"
                },
                "message": {
                    "description": "pesan error untuk dikirimkan ke pengelola",
                    "type": "string"
                }
            }
        },
        "public.TInfoEarthquake": {
            "type": "object",
            "properties": {
                "affected": {
                    "description": "affected",
                    "type": "string"
                },
                "coordinates": {
                    "description": "koordinat",
                    "type": "string"
                },
                "depth": {
                    "description": "meter",
                    "type": "integer"
                },
                "information": {
                    "description": "information",
                    "type": "string"
                },
                "latitude": {
                    "description": "garis lintang",
                    "type": "number"
                },
                "longitude": {
                    "description": "garis bujur",
                    "type": "number"
                },
                "magnitude": {
                    "description": "magnitudo (SR)",
                    "type": "number"
                },
                "time": {
                    "description": "unix timestamp (utc)",
                    "type": "integer"
                }
            }
        },
        "public.TInfoTAWiki": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "urutan",
                    "type": "integer"
                },
                "tahukah_anda": {
                    "description": "informasi",
                    "type": "string"
                }
            }
        },
        "public.TResLatestEarthquake": {
            "type": "object",
            "properties": {
                "info": {
                    "description": "latest earthquake information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/public.TInfoEarthquake"
                        }
                    ]
                },
                "peta_gempa": {
                    "description": "latest earthquake map",
                    "type": "string"
                }
            }
        },
        "public.TResTAWiki": {
            "type": "object",
            "properties": {
                "image_link": {
                    "description": "tautan gambar (opsional)",
                    "type": "string"
                },
                "info": {
                    "description": "data \"tahukah anda\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/public.TInfoTAWiki"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "name": "basic"
        },
        {
            "description": "API untuk mendapatkan suatu informasi seperti fakta unik, berita terkini, atau informasi darurat seperti gempa bumi",
            "name": "informasi"
        },
        {
            "description": "API yang masih dalam tahap pengembangan",
            "name": "beta"
        }
    ],
    "x-tagGroups": [
        {
            "name": "API",
            "tags": [
                "basic"
            ]
        },
        {
            "name": "Daily",
            "tags": [
                "information"
            ]
        }
    ]
}`

// SwaggerInfopublic holds exported Swagger Info so clients can modify it
var SwaggerInfopublic = &swag.Spec{
	Version:          "BETA",
	Host:             "cinnabar.icaksh.my.id",
	BasePath:         "/public",
	Schemes:          []string{},
	Title:            "Cinnabar Public REST API",
	Description:      "# Introduction (OpenAPI Specification)\nCinnabar Public REST API merupakan API publik yang tersedia untuk umum dan dapat digunakan secara gratis. Dokumentasi API ini merupakan dokumentasi Cinnabar REST API untuk publik. Apabila anda ingin melihat dokumentasi Cinnabar REST API yang privat, silakan menuju tautan [Cinnabar Private REST API -  Documentation](https://cinnabar.icaksh.my.id/private/docs).\nAPI ini didokumentasikan dalam bentuk **OpenAPI format** dan didasarkan pada [swagger.io](https://swagger.io). Halaman dokumentasi ini digenerate dengan menggunakan [swaggo](https://github.com/swaggo/swag) dan dipublikasikan menggunakan [redoc](https://github.com/Redocly/redoc).\n# Cross-Origin Resource Sharing\nAPI ini memiliki fitur Cross-Origin Resource Sharing (CORS) yang diterapkan sesuai dengan [spesifikasi W3C](https://www.w3.org/TR/cors/) dan memungkinkan komunikasi lintas domain. Semua response bersifat publik dan dapat diakses oleh semua orang dari aplikasi apapun ataupun website apapun.\n# Information\nAPI ini masih dalam tahap pengembangan. Apabila anda ingin memberikan saran terhadap pengembangan API ini, silakan hubungi alamat pos-el yang telah tersedia. Jangan sungkan untuk menghubungi alamat pos-el jika terjadi error.\n# Donation\nPada dasarnya anda dapat menggunakan REST API ini secara gratis. Perlu diketahui bahwa Cinnabar Public REST API di-deploy di Google Cloud Run Free Tier dan hingga saat ini biaya yang dikeluarkan hanya terfokus pada pembelian bandwith ke Indonesia (sekitar Rp1500/GB) sehingga kami tidak membuka donasi dan kami harap anda tidak melakukan hal yang mengakibatkan tingginya bandwith keluar.",
	InfoInstanceName: "public",
	SwaggerTemplate:  docTemplatepublic,
}

func init() {
	swag.Register(SwaggerInfopublic.InstanceName(), SwaggerInfopublic)
}
